### ISSUE TITLE
Creo que está mal importada la lista

### ISSUE THREAD

**Issue by natoszme** [ezecastiglione18/Pdepflix-Elm#2]
https://github.com/ezecastiglione18/Pdepflix-Elm/blob/8eb4e27356c1f62e3d99a8802baf051789500fd3/src/Backend.elm#L11

En el tp dice 

> En todos los casos hay que importarlas, de la siguiente manera: 

`import List exposing (intersperse)`

**Comment by ezecastiglione18** [comment]
Y dentro del () iria filter, map, contains, etc?

**Comment by natoszme** [comment]
No dije nada, la lista se importa sola!
