### ISSUE TITLE
Estás queriendo usar sortBy, no sort

### ISSUE THREAD

**Issue by natoszme** [ezecastiglione18/Pdepflix-Elm#3]
https://github.com/ezecastiglione18/Pdepflix-Elm/blob/8eb4e27356c1f62e3d99a8802baf051789500fd3/src/Backend.elm#L50

([sortBy](https://package.elm-lang.org/packages/elm/core/latest/List#sortBy) te deja pasarle una función comparadora)

**Comment by ezecastiglione18** [comment]
Ah yo pense que el sortBy no existia. Ahi lo modifico
